runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: happyblogging.wsgi.application
  login: required

# Only pure Python libraries can be vendored
# Python libraries that use C extensions can
# only be included if they are part of the App Engine SDK 
libraries:
- name: django
  version: 1.9

env_variables:
  DJANGO_SETTING_MODULE: 'happyblogging.settings'
